# -*- coding: utf-8 -*-
"""ComunicacaoDados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLPR7S2l077A_PlUcVIayNwIi71qXXrR
"""

def criptografia(s):
    chars = []
    for c in s:
        chars.append(chr(ord(c) + 1))
    return ''.join(chars)[::-1]

def descriptografia(s):
    chars = []
    for c in s[::-1]:
        chars.append(chr(ord(c) - 1))
    return ''.join(chars)

def stringParaBits(s):
    result = []
    for c in s:
        bits = bin(ord(c))[2:]
        bits = '00000000'[len(bits):] + bits
        result.extend([int(b) for b in bits])
    return result

def bitsParaString(bits):
    chars = []
    for b in range(int(len(bits) / 8)):
        byte = bits[b*8:(b+1)*8]
        chars.append(chr(int(''.join([str(bit) for bit in byte]), 2)))
    return ''.join(chars)

def bitsParaAMI(bits):
    result = []
    n = 1
    for b in range(len(bits)):
        if bits[b] == 1:
            result.append(n)
            n = -n
        else:
           result.append(0)
    return result

def AMIParaBits(bits):
    result = []
    for b in range(len(bits1)):
        if bits1[b] == 0:
            result.append(0)
        else:
           result.append(1)
    return result

string1 = input('Digite a mensagem: ')#"ola"

string2 = criptografia(string1)
print('\nMensagem criptografada: ',string2)

bits1 = stringParaBits(string2)
print('Sequência de bits: ',bits1)

bits2 = bitsParaAMI(bits1)
print('AMI: ',bits2)

bits3 = AMIParaBits(bits2)
print('\nDesfazendo AMI: ',bits3)

string3 = bitsParaString(bits1)
print('Voltado para string: ',string3)

string4 = descriptografia(string3)
print('Descriptografando: ',string4)